### ISSUE TITLE
A better way to use a variable in WHERE clause

### ISSUE THREAD

**Issue by doyonghoon** [huandu/go-sqlbuilder#101]
While I was reviewing the PR #98, running the changes on my local machine I wanted to clear my wonder about the desired usage of `WHERE` clause.

PrestoSQL is subtly sensitive to a data type in a `WHERE` clause. Suppose given a column `id` is an integer, we have a following query:

```sql
SELECT * FROM customer WHERE id = '1';
```

This `SELECT` statement wouldn't be a problem as it will return a desired result when running in MySQL, but it is not a runnable query in PrestoSQL because it is comparing an integer field "id" with a string literal '1'.

Closer looking at the argument '1', it may be replaced with another variable referred to as a foreign key so that the argument should not be wrapped with apostrophes (`'`). With that in mind though, the following code will generate a query that does not run in PrestoSQL.

```golang
sb := NewSelectBuilder()
sb.Select(...)
sb.Where(sb.Equal("id", "other_table.id"))
```

That is because the variable `other_table.id` will be wrapped by apostrophes `'`, and PrestoSQL will eventually reject the query as it violates the data type matching. I have a sense that this problem won't be a sole problem for PrestoSQL, so just wanted to have an attention to have what the best practices will be.

For now, I am coding like the following by the way:

```golang
sb.Where("id = other_table.id")
```

Any suggestions to make it syntatically more formal and to make it much elegant will be appreciated. Thanks!

**Comment by huandu** [comment]
Thanks for raising this issue to me. Your thoughts are really valuable for me to understand how the package users feel about the design.

First, let me show you my suggestion on how to build WHERE clause with `other_table.id`. Don't feel surprised - I'd recommend to write code exactly like what you do.

```go
sb.Where("id = other_table.id")
```

As this package is solely designed to build SQL *string*, when we don't need to escape anything, it's OK and recommended to write plain SQL. It's safe and reads well.

Second, regarding to the data type problem, it's developer's responsibility to call `sb.Equal()` with correct data type. In your case, we should call `sb.Equal` with integer `1` instead of a string.

If the value is not a scalar value, e.g. `a = b + "unsafe-data"`, we can build this condition like following.

```go
data := "some data" // Data comes from a user and should be escaped.
sb.Where("a = b + " + sb.Var(data)) // Oh yeah, just simply concat strings.
```

Finally, I'd like to share some thoughts about current package design.

My ideal design is to provide developers a type-safe and easy-to-read SQL building experience with full IDE support (e.g. auto complete for all clauses). However, due to lack of syntax candy in Go, it's really hard to balance everything. My current priority is type-safe, easy-to-read and then IDE support.

I don't think the design of this package is good enough. If I know how to make it more elegant, I'll do it with no doubt.

If you have any API design proposal which can make your experience better as a developer, feel free to let me know. I'm open to any idea.

**Comment by huandu** [comment]
I close this issue as there is no update for a week. Feel free to reopen it if you have more thoughts. 😄
