### ISSUE TITLE
Needs JOIN syntax for SQL query

### ISSUE THREAD

**Issue by vvasystem** [huandu/go-sqlbuilder#13]
Do you plan to do JOIN?

**Comment by huandu** [comment]
There was no plan in the past. However, I can plan it now. :)

**Comment by ivanjaros** [comment]
I have a big project built with this and now I truly need joins. I will have to switch to different library. My fault that I haven't explored this library before using it more. SQL whiteout joins is like coffee without cream .

**Comment by huandu** [comment]
@ivanjaros Can you please be more specific about how to use JOIN, e.g. let me know some sample SQLs? I was too busy to implement this feature with a well-thought design. I think I can use your input to submit a quick solution.

**Comment by ivanjaros** [comment]
I think something like NewSelectBuilder().Select().From().LefTJoin().Where()...
I am not in process of swapping out go-sqlbuilder for https://github.com/Masterminds/squirrel though.

**Comment by huandu** [comment]
@ivanjaros Thanks for your feedback. I investigated squirrel before I started to implement this package. The major difference between these two packages is that this package provides more flexible builders like `Build` and `Buildf` so that there should be no need for me to implement all kinds of SQL syntax. As you know, SQL syntax is complex and inconsistent among different DBMS.

Anyway, I'll submit a squirrel-like JOIN api very soon.

**Comment by huandu** [comment]
Here is a sample. https://godoc.org/github.com/huandu/go-sqlbuilder#example-SelectBuilder--Join

**Comment by ivanjaros** [comment]
PS: coming from PHP and Drupal, I haven't found a good alternative for Drupal's DB layer and one thing that would be great to have is that when you are providing a table, there should be an optional second argument for alias. If empty, it should equal to table name. As for fields, each non-prefixed field(foo.bar) should be parsed into using the active/default table. Like Select("foo").From("bar") -> "select bar.foo from bar" or Select("b.foo").From("bar", "b") -> "select b.foo from bar as b". Also, for joins, the same applies: Select("b.foo", "f.baz").From("bar", "b").LeftJoin("baz", "f", "using id") -> "select b.foo, f.baz from bar as b left join baz as f using (id)".

**Comment by huandu** [comment]
@ivanjaros  I don't understand why we should add table name in column names. If it's a simple SELECT without JOIN or nested SELECT, it's exactly the same to add or not to add table name so that this feature is not necessary. If it's not simple, just like your last case,  it seems impossible to guess the table name of a column so that sql builder cannot help us.
