### ISSUE TITLE
How to get full raw sql query with arguments merge into it

### ISSUE THREAD

**Issue by khanakia** [huandu/go-sqlbuilder#143]
I am using this example and it returns the args separately but I want to merge them within sql
```go
sb := sqlbuilder.NewSelectBuilder()
sb.SQL("SELECT id, name FROM user").Where(
sb.In("id", 1, 2, 3),
)

s, args := sb.Build()
fmt.Println(s)
fmt.Println(args)
```

```
SELECT id, name FROM user WHERE id IN (?, ?, ?)
[1 2 3]
```

I want the SQL return as belown. how to achieve this ?
```sql
SELECT id, name FROM user WHERE id IN (1, 2, 3)
```

**Comment by huandu** [comment]
You can use [interpolate feature](https://pkg.go.dev/github.com/huandu/go-sqlbuilder#readme-interpolate-args-in-the-sql) in this package.

**Comment by huandu** [comment]
Interpolation for ClickHouse is NOT supported correctly right now, though there is a method named `ClickHouse.Interpolate()` which is almost an alias of `MySQL.Interpolate()`.

The interpolation feature is designed to build SQL for some SQL-like APIs, e.g. SQL for ES or SQL for Redis, in which there are no built-in interpolation support in their drivers. It's out of scope of this package to implement full-featured interpolation on par with DBMS driver. I haven't finished ClickHouse interpolation because of the complexity.

**Comment by khanakia** [comment]
Got it. Thanks
