### ISSUE TITLE
`OR`ing where clauses

### ISSUE THREAD

**Issue by jakegut** [huandu/go-sqlbuilder#156]
I have a situation where I'd like like to `OR` a number of where clauses but I'm unable to find a way to do that.

The closest I've gotten to is
```go
sb := sqlbuilder.NewSelectBuilder()
exprs := []string{}
for _, or := range orExpressions {
  expr, err := or.SqlExpression() // returns (*sqlbuilder.SelectBuilder, error)
  if err != nil {
    return nil, err
  }
  exprs = append(exprs, sb.Var(expr))
}

sb.Where(sb.Or(exprs...))

return sb, nil
```

but this prepends `WHERE ` for each expression: `WHERE (WHERE column='value' OR WHERE column='other_value')`

Is there a better way to do this?

**Comment by huandu** [comment]
It's recommended to use plain string for expressions rather than builders, which are designed to build statements.

I don't know the exact definition of `orExpressions`. I guess it should be a slice of struct, in which there is a method `SqlExpression()` to create `SelectBuilder`. My recommendation is to add a new parameter `cond *sqlbuilder.Cond` to the method and change the return type to `string`. The method should use `cond` to build expression string.

With this change, your code can be updated like following.

 ```go
sb := sqlbuilder.NewSelectBuilder()
exprs := []string{}
for _, or := range orExpressions {
  expr, err := or.SqlExpression(sb.Cond) // returns (string, error)
  if err != nil {
    return nil, err
  }
  exprs = append(exprs, expr)
}

sb.Where(sb.Or(exprs...))
```

**Comment by jakegut** [comment]
Thanks for the recommendation, we used a variant of it and it's working fo us. Thanks!
