### ISSUE TITLE
JSON_TABLE issue

### ISSUE THREAD

**Issue by srzkptrsk** [huandu/go-sqlbuilder#19]
Input:
`sb.From("warehouse",` "JSON_TABLE(data, '$[*]' COLUMNS (id JSON PATH '$.id')) AS warehouseJson")`

Output:
`FROM warehouse, JSON_TABLE(data, '[*]' COLUMNS (id JSON PATH '.id')) AS warehouseJson`

"$" is missing :-/

**Comment by huandu** [comment]
I see. It's a bug. I'll unescape `$` in this case.

**Comment by huandu** [comment]
@srzkptrsk After I reconsider this case, I find that it's better to use the method `Escape` explicitly in your code instead of changing `sqlbuilder` package.

Here is the recommended change in your code.

```go
sb.From("warehouse", sb.Escape("JSON_TABLE(data, '$[*]' COLUMNS (id JSON PATH '$.id')) AS warehouseJson"))
```

The example [SELECT advanced usage](https://godoc.org/github.com/huandu/go-sqlbuilder#example-SelectBuilder--AdvancedUsage) shows the scenario in which table name can contain `$`.

**Comment by huandu** [comment]
The PR #20 ensures that `$` in your case will be printed as it is in result. However, I still recommend you to use `Escape` explicitly to avoid unintentional error.

Close this issue. If you still have any problem, free feel to reopen it.

**Comment by srzkptrsk** [comment]
Thanks a lot! Ps. great package!
