### ISSUE TITLE
Order By doesn't work with multiple columns and different sorting

### ISSUE THREAD

**Issue by califlower** [huandu/go-sqlbuilder#24]
`SELECT name, species, birth FROM pet
       ORDER BY species DESC, birth DESC`

I cannot seem to find a good way to write this. I can do `orderBy(species, birth).Desc()` but that's different. That's the equivalent of 

`SELECT name, species, birth FROM pet
       ORDER BY species ASC, birth DESC`

**Comment by califlower** [comment]
To anyone confused, you can do `orderBy("species desc", "birth desc")`

**Comment by huandu** [comment]
You are right. To build SQL like `ORDER BY species DESC, birth DESC`, we need to use either

```go
sb.OrderBy("sepcies DESC", birth").Desc()
```

or

```go
sb.OrderBy("sepcies DESC", "birth DESC") // It's not recommended though.
```

I don't add `DESC` to all `OrderBy` arguments just because I don't want to add any magic in this package -- every method just build SQL as what we write explicitly.

I believe that calling `OrderBy("a", "b", "c").Desc()` should build SQL  `ORDER BY a, b, c DESC`. No more and no less from any perspective.
