### ISSUE TITLE
Auto create table builder by fields in struct

### ISSUE THREAD

**Issue by writerim** [huandu/go-sqlbuilder#34]
```golang
type User struct{
  ID int `db:"id" sqldb:"int(11)"`
  Login string `db:"login" sqldb:"varchar(255)"`
}

ctb := sqlbuilder.NewCreateTableBuilder()
// compile struct to ctb obj
ctb = ctb.IfNotExists()
println(ctb.String())
// CREATE TABLE IF NOT EXISTS ...
```

**Comment by huandu** [comment]
I considered this feature in the past. I didn't implement it due to following reasons.

* Column definitions could be quite long, e.g. `BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT "comments..."` so it's not easy to read and maintain in field tag. Simpleness and readability is the top design goal in this package.
* There is no way to represent keys in field tag. We still need to call `CreateTableBuilder#Define` to define keys. If so, I prefer to define all table columns by `Define` as it's clearer.

**Comment by huandu** [comment]
Please let me know your thought.

**Comment by writerim** [comment]
My suggestion is to use the following rules:
1. When the field ends with the suffix <table> _id automatically associate this with the table <table>
2. The id field is always AI PRIMARY
3. The type of the string field is always varchar (255)
4. Field int - always int (255)

This will make it possible for simple projects to automatically generate tables. For more complex projects, it makes sense to use more complex libraries. Use of this feature is at the discretion of the user.

**Comment by huandu** [comment]
The suggested rules are not well defined and extensible. They are project-specific features which work only for quite a limit number of projects.

As all rules can be implemented outside this package, e.g. call `Define` after analyzing struct field tags, I still suggest "won't fix" in this package and do it separately. It's welcome to create a separate package for this feature. I can list the package in the README as an extension for this package.

**Comment by writerim** [comment]
This is a good idea.
