### ISSUE TITLE
PostgreSQL.Interpolate escape ' wrong.

### ISSUE THREAD

**Issue by zhyon404** [huandu/go-sqlbuilder#37]
after call Interpolate, i got `ERROR:  syntax error at or near "BUNADH介绍"`.

got  `'A\'BUNADH介绍'` in log, which should be ``'A''BUNADH介绍'``

**Comment by huandu** [comment]
Can you please let me know your full SQL statement? I can use it as a case to test my fix.

**Comment by zhyon404** [comment]
```
text:="A'BUNADH介绍"
sb := sqlbuilder.PostgreSQL.NewInsertBuilder()
sb.InsertInto("test").
	Cols("text").
	Values(text)
sql, err := sqlbuilder.PostgreSQL.Interpolate(sb.Build())
```
@huandu something like this

**Comment by huandu** [comment]
Is it OK to add `E` prefix in front of a string with escape sequence instead of using double single quote (`''`)? I check related [PostgreSQL document](https://www.postgresql.org/docs/9.2/sql-syntax-lexical.html#SQL-SYNTAX-STRINGS-ESCAPE) and find that `\'` is not the only escape sequence not supported by PostgreSQL by default. If we need to support all standard escape sequences,  adding `E` is required.
