### ISSUE TITLE
Support different order on different columns

### ISSUE THREAD

**Issue by WangBeyond** [huandu/go-sqlbuilder#44]
Currently it only supports a single order for whole select builder. Can we support different order on different columns? Something like

``
sb.OrderBy("col1").Asc().OrderBy("col2").Desc()
``

**Comment by huandu** [comment]
It's supported. Remember that `go-sqlbuilder` *is* a string builder. You can write arbitrary SQL expression as string instead of calling lots of helper methods.

```go
sb.OrderBy("col1 ASC", "col2 DESC")
```

**Comment by WangBeyond** [comment]
Yah I know technically it's supported ... just wondering whether we can support it in more "native" way

**Comment by huandu** [comment]
You can see discussion in issue #24. I don't mind to add more "native" method. I do mind to make code *read* right.

For SQL `ORDER BY col1 ASC, col2 DESC`, both `sb.OrderBy("col1 ASC", "col2").Desc()` and `sb.OrderBy("col1 ASC", "col2 DESC")` are OK, but `sb.OrderBy("col1").Asc().OrderBy("col2").Desc()` is not - because the last one is read like `ORDER BY col1 ASC ORDER BY col2 DESC`.
